name: kapp-controller release

on:
  push:
    tags:
      - 'v*'

jobs:
  kapp-controller-release:
    name: kapp-controller release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          path: src/github.com/${{ github.repository }}
      - name: Install Carvel Tools
        uses: vmware-tanzu/carvel-setup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          only: ytt, kbld
          ytt: v0.35.1
          kbld: v0.30.0
      - name: Run release script
        env:
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          set -e -x

          # TODO: Update login process once new registry
          # is chosen. See https://github.com/vmware-tanzu/carvel-kapp-controller/issues/319.
          docker login -u k14s -p "$REGISTRY_PASSWORD"

          ./hack/build-release.sh

      - name: Upload release yaml to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: release.yml
          path: ./tmp/release.yml
